import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

// const pacifico = Pacifico({
//   weight: "400",
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-pacifico",
// });

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Readdy Site",
  description: "Generated by Readdy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${inter.variable} ${poppins.variable} antialiased font-inter`}
      >
        {children}
      </body>
    </html>
  );
}
